### ISSUE TITLE
Third party Dependency in Plugin

### ISSUE THREAD

**Issue by Prashanttorat** [pf4j/pf4j-spring#19] opened 2018-08-21 10:14 UTC
i am not aware of how to add dependency in plugin!

i am facing issue while adding third party jar "apache poi" in plugin, i have added maven dependency in pom file, i am able to build plugin jar file but getting ClassnotFound exception at run time

**Comment by decebals** [comment] 2018-08-26 18:34
Can you add more detail please? Can you share with us the plugin's pom.xml? Maybe you create a thin jar and not a fat jar. Please take a look at your plugin's jar and see if the find the POI's classes.

**Comment by decebals** [comment] 2018-09-12 03:48
@Prashanttorat 
Did you solved the problem?

**Comment by decebals** [comment] 2018-12-11 18:16
I suppose that the problem is solved in the meantime so I will close the issue. If you consider that you need more information, please open it.

**Closed by decebals** 2018-12-11 18:16 UTC

**Comment by MohankumarD** [comment] 2019-02-14 11:19
Hi Decebals,
I am facing the same issue, can you please help on this how to add a dependency for third-party jar..
